import Protected from '@/components/Providers/Protected'
import Provider from '@/components/Providers/Provider'
import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Provider>  
      <Protected>
      {children}
      </Protected>
      </Provider>
    </div>
  )
}
