import Provider from "@/components/Providers/Provider";
import "../globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import Sidebar from "@/components/Layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <div className=" h-screen ">
            <div className=" h-full mx-auto ">
              <div className="grid grid-cols-4 h-full overflow-">
                <Sidebar />
                <div
                  className="
                  col-span-3 
                  lg:col-span-2
                  border-x-[1px]
                  border-neutral-800

                  "
                >
                  {children}
                </div>
                <div className=" hidden lg:block">
                  ihsuidf
                </div>
              </div>
            </div>
          </div>
        </body>
      </Provider>
    </html>
  );
}
