import Provider from "@/components/Providers/Provider";
import "../globals.css";
export const metadata = {
  title: "Blogs",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" bg-black min-h-screen">
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
